server:
  port: 8081
spring:
  openapi:
    generator:
      java:
        postProcessFile: google-java-format
  application:
    name: mod-mylibrary
  datasource:
    username: ${DB_USERNAME:okapi}
    password: ${DB_PASSWORD:okapi25}
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_DATABASE:okapi}
  sql:
    init:
      # to boot up application despite of any DB connection issues
      continue-on-error: true
  jpa:
    database-platform: org.hibernate.dialect.~
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
        format_sql: true
    show-sql: true
  liquibase:
    change-log: classpath:db/changelog/changelog-master.xml
    enabled: true
  jackson:
    default-property-inclusion: non_empty
    deserialization:
      fail-on-unknown-properties: false
      accept-single-value-as-array: true
  mustache:
    check-template-location: false
folio:
  tenant:
    validation:
      enabled: true
management:
  endpoints:
    web:
      exposure:
        include: info,health,env,httptrace
      base-path: /admin
  #  endpoint:
  #    health:
  #      show-details: always
  #      show-components: always
  ###################################################
  # Disable all checks except for readiness
  ###################################################
  health:
    defaults:
      enabled: false
    readinessstate:
      enabled: true
debug: false
